server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: BookStore
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html  

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Exposes all available actuator endpoints
  endpoint:
    shutdown:
      enabled: true  # Explicitly enable the shutdown endpoint
logging:
  level:
    org:
      springframework: DEBUG
      thymeleaf: DEBUG
      
