server:
  port: 8082  # Application will run on port 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Controls schema generation (update, validate, create, create-drop)
    show-sql: true       # Enables SQL query logging
    properties:
      hibernate:
        format_sql: true # Formats SQL queries for better readability

  application:
    name: BookStore  # Application name

  thymeleaf:
    prefix: classpath:/templates/  # Location of Thymeleaf templates
    suffix: .html                  # Template file extension

management:
  endpoints:
    web:
      exposure:
        include: '*'  # Expose all Actuator endpoints
  endpoint:
    shutdown:
      enabled: true    # Enable the shutdown endpoint

logging:
  level:
    org.springframework: DEBUG  # Debug level for Spring logs
    thymeleaf: DEBUG            # Debug level for Thymeleaf logs
